apiVersion: v1
kind: Service
metadata:
  name: pixafrontend
spec:
  type: LoadBalancer
  selector:
    app: pixafrontend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixafrontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pixafrontend
  template:
    metadata:
      labels:
        app: pixafrontend
    spec:
      containers:
      - name: pixafrontend
        image: charliereign/pixagram_front
        env:
        - name: REACT_APP_FRONTEND_BASE_URL
          value: "http://localhost:3000/"
        - name: REACT_APP_BACKEND_BASE_URL
          value: "http://localhost:8000/"
        # imagePullPolicy: Always 
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
